# Generated by Django 3.0.6 on 2020-05-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
