# Generated by Django 3.0.6 on 2020-05-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfprofile', '0002_auto_20200512_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
