# Generated by Django 3.0.6 on 2020-05-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfprofile', '0003_auto_20200513_1544'),
        ('courses', '0003_auto_20200507_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_to_play', models.DateField()),
                ('tee_time', models.TimeField()),
                ('booked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfprofile.UserProfile')),
            ],
        ),
    ]
