# Generated by Django 3.0.6 on 2020-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_teetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teetime',
            name='day_to_play',
        ),
        migrations.AlterField(
            model_name='teetime',
            name='tee_time',
            field=models.DateTimeField(),
        ),
    ]
