# Generated by Django 3.0.6 on 2020-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200513_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='teetime',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
