# Generated by Django 3.0.6 on 2020-05-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('golfprofile', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_greenfee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TeeTimePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_greenfee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('payment_info', models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='paygreenfee.PaymentInfo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfprofile.UserProfile')),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.TeeTime')),
            ],
        ),
    ]
