# Generated by Django 3.0.6 on 2020-05-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_teetime_price'),
        ('golfprofile', '0003_auto_20200513_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeeTimePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_greenfee', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfprofile.UserProfile')),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.TeeTime')),
            ],
        ),
    ]
