# Generated by Django 3.0.6 on 2020-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygreenfee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teetimepurchase',
            name='order_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
