# Generated by Django 3.0.6 on 2020-05-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygreenfee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='total_greenfee',
            new_name='total_price',
        ),
    ]
