# Generated by Django 3.0.6 on 2020-05-15 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paygreenfee', '0002_teetimepurchase_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teetimepurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time'),
            preserve_default=False,
        ),
    ]
