# Generated by Django 3.0.6 on 2020-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygreenfee', '0003_teetimepurchase_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_greenfee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='teetimepurchase',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='teetimepurchase',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='teetimepurchase',
            name='total_greenfee',
        ),
    ]
