# Generated by Django 3.0.6 on 2020-05-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygreenfee', '0003_auto_20200519_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teetimepurchase',
            old_name='total_greenfee',
            new_name='greenfee',
        ),
        migrations.RemoveField(
            model_name='teetimepurchase',
            name='player',
        ),
    ]
