# Generated by Django 3.0.6 on 2020-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygreenfee', '0004_auto_20200518_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='teetimepurchase',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teetimepurchase',
            name='total_greenfee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='total_greenfee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
